- name: PostgreSQL , repmgr and Barman Configuration for streaming replication
  hosts: standby1
  become: true
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  vars_files:
   - node.yml
  tasks:
  - name: Create database
    become: true
    become_user: postgres
    command: psql -c "CREATE DATABASE best";
    register: create_db
    failed_when: "'FAILED' in create_db.stderr"

  - name: Create table t1 
    become: true
    become_user: postgres
    command: psql -d best -U postgres  -c "  CREATE TABLE t1(a int); INSERT INTO t1(a) SELECT * FROM generate_series(1,100000)";
    register: t1_create
    failed_when: "'FAILED' in t1_create.stderr"

  - name: Create table t2 
    become: true
    become_user: postgres
    command: psql -d best -U postgres  -c " CREATE TABLE t2(a int); INSERT INTO t2(a) SELECT * FROM generate_series(1,100000)";
    register: t2_create
    failed_when: "'FAILED' in t2_create.stderr"

  - name: Create table t3 
    become: true
    become_user: postgres
    command: psql -d best -U postgres  -c " CREATE TABLE t3(a int); INSERT INTO t3(a) SELECT * FROM generate_series(1,100000)";
    register: t3_create
    failed_when: "'FAILED' in t3_create.stderr"
