  - name: barman repository
    shell: curl https://dl.2ndquadrant.com/default/release/get/{{ pg_version }}/rpm | sudo bash
    args:
     warn: no

  - name: barman installation
    yum:
     name: "{{ item }}"
     state: present
    loop:
    - barman-{{ barman_version }}
    - barman-cli-{{ barman_version }}
