# **************************************** barman  DB and user creation  ********************************************
  - name: barman user creation
    become: true
    become_user: postgres
    command: createuser -s -w "{{barman_user}}" -p {{ pg_port }}
    when: ansible_nodename == "node1"


  - name: Set privileges to barman user
    become: true
    become_user: postgres
    command: psql -p {{ pg_port }} -c "GRANT EXECUTE ON FUNCTION pg_start_backup(text, boolean, boolean) to {{barman_user}};
                      GRANT EXECUTE ON FUNCTION pg_stop_backup() to {{barman_user}};
                      GRANT EXECUTE ON FUNCTION pg_stop_backup(boolean, boolean) to {{barman_user}};
                      GRANT EXECUTE ON FUNCTION pg_switch_wal() to {{barman_user}};
                      GRANT EXECUTE ON FUNCTION pg_create_restore_point(text) to {{barman_user}};
                      GRANT pg_read_all_settings TO {{barman_user}};
                      GRANT pg_read_all_stats TO {{barman_user}}; "
    when: ansible_nodename == "node1"

  - name: Steraming barman user creation
    become: true
    become_user: postgres
    command: createuser -p {{ pg_port }} -w --replication "{{barman_streaming_user}}"
    when: ansible_nodename == "node1"

