# *************************************PostgreSQL Repository and Installation || INSTALL POSTGRESQL****************************

  - name: Install postgres  repository
    dnf:
     name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
     state: present
    when: ansible_nodename != "pgpool1" or ansible_nodename != "pgpool2"

  - name: postgres default module disabled
    command: dnf -qy module disable postgresql
    when: ansible_nodename != "pgpool1" or ansible_nodename != "pgpool2"

  - name: remove data directory if exists
    become: true
    file: path=/var/lib/pgsql/{{ pg_version }}/data state=absent
    when: ansible_nodename != "pgpool1" or ansible_nodename != "pgpool2"

  - name: install postgresql server and contrib
    yum: 
     name: "{{ item }}"
     state: installed
    loop:
    - postgresql{{ pg_version }}-server
    - postgresql{{ pg_version }}-contrib
    when: ansible_nodename != "pgpool1" or ansible_nodename != "pgpool2"


