  - name: Configure pgbouncer  | PGBOUCNER WITH PGPOOL NODE
    become: true
    become_user: root
    blockinfile:
     dest: /etc/pgbouncer/pgbouncer.ini
     marker: "# {mark} ANSIBLE MANAGED BLOCK insertion 1"
     block: |
        #************** pgpool basic configuration

        [databases]
        * = host=10.16.71.181 port=9999
        [users]
        [pgbouncer]
        logfile = /var/log/pgbouncer/pgbouncer.log
        pidfile = /var/run/pgbouncer/pgbouncer.pid
        listen_addr = *
        listen_port = 6432
        auth_type = scram-sha-256
        auth_file = /etc/pgbouncer/userlist.txt
        admin_users = pgbouncer
        stats_users = stats, pgbouncer,postgres
        pool_mode = transaction
        ignore_startup_parameters = extra_float_digits
        max_client_conn = 200
        default_pool_size = 50
        reserve_pool_size = 25
        reserve_pool_timeout = 3
        server_lifetime = 3600
        server_idle_timeout = 600
        server_connect_timeout = 15
        server_login_retry = 2
        query_timeout = 60
        query_wait_timeout = 60
        client_idle_timeout = 60
        client_login_timeout = 60
        tcp_keepalive = 1
        tcp_keepcnt = 1
        tcp_keepidle = 5
        tcp_keepintvl = 2
        tcp_user_timeout = 30

    when: ansible_nodename == "pgpool1" or ansible_nodename == "pgpool2"

