# **************************************** DTABASE  Repmgr DB and User Creation *****************************************

  - name: repmgr user creation | DB USER WITNESS 1
    command: createuser --superuser "{{repmgr_user}}" -w
    become: true
    become_user: postgres
    when: ansible_nodename == "pgbackup"

  - name: repmgr db creation | DB DATABASE WITNESS 1
    become: true
    become_user: postgres
    command: createdb --owner="{{repmgr_user}}" "{{repmgr_db}}"
    when: ansible_nodename == "pgbackup"

  - name: repmgr default search path | DB DEFAULT SEARCH PATH WITNESS 1
    become: true
    become_user: postgres
    command: psql -c "ALTER USER {{repmgr_user}} SET search_path TO {{repmgr_db}}, public;"
    when: ansible_nodename == "pgbackup"


