  - name: repmgr start for node2 | REPMGR NODE2 START
    become: true
    become_user: root
    service:
     name: repmgr{{ pg_version }}
     state: started
     enabled: yes
    ignore_errors: yes
    when: ansible_nodename == 'node2'


