---
- name: sudo user postgres | SUDO USER
  become: true
  become_user: root
  lineinfile:
   path: /etc/sudoers
   #regexp: '^%wheel '
   insertafter: '^# %wheel ALL='
   line: 'postgres ALL=(ALL) NOPASSWD: ALL'
   validate: /usr/sbin/visudo -cf %s
  when: ansible_nodename != 'barman'

- name: sudo user barman | SUDO USER
  become: true
  become_user: root
  lineinfile:
   path: /etc/sudoers
   insertafter: '^# %wheel ALL='
   line: 'barman ALL=(ALL) NOPASSWD: ALL'
   validate: /usr/sbin/visudo -cf %s
  when: ansible_nodename == 'barman'
