# ****************************************PostgreSQL pg_hba.conf file configuration**********************************************

  - name: add new configuration to "pg_hba.conf"
    blockinfile:
     dest: /var/lib/pgsql/{{ pg_version }}/data/pg_hba.conf
     block: |
         local   replication     all                                     peer
         local   postgres        postgres                                trust
         host    replication     all             127.0.0.1/32            ident
         host    replication     all             ::1/128                 ident
         host    replication     repmgr            {{subnet}}              trust
         host    replication     streaming_barman  {{subnet}}            trust

         local  repmgr           repmgr                                  trust
         host   repmgr           repmgr          127.0.0.1/32            trust
         host   repmgr           repmgr            {{subnet}}            trust
         host   all              barman            {{subnet}}            trust
         host   replication      streaming_barman  {{subnet}}            trust
    when: ansible_nodename == "node1"

