---
# handlers file for database_solution
  - name: start_postgres
    become: true
    service:
     name: postgresql-{{ pg_version }}.service
     state: started
     enabled: yes

  - name: restart_postgres
    become: true
    service:
     name: postgresql-{{ pg_version }}.service
     state: restarted

  - name: start_repmgr
    become: true
    become_user: root
    service: 
     name: repmgr-{{ pg_version }}.service
     state: started
     enabled: yes

  - name: restart_repmgr
    become: true
    become_user: root
    service: 
     name: repmgr-{{ pg_version }}.service
     state: restarted
